# Generated by Django 3.2.9 on 2021-12-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_habit_record'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='habit_id',
            new_name='habit',
        ),
        migrations.AlterField(
            model_name='habit',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
