# Generated by Django 3.2.9 on 2021-12-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211203_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
