# Generated by Django 4.0 on 2021-12-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_record_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='duration',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='goal_unit',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
