# Generated by Django 4.0 on 2021-12-08 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_record_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ('name',)},
        ),
    ]
